user:
  target: default
  outputs:
    default:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SECRET_ACCOUNT') }}"
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      role: ACCOUNTADMIN
      warehouse: MEMPOOL
      database: MEMPOOL_DB
      schema: mempool_dbt
      threads: 6
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      retry_on_database_errors: true
